version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mvp-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mvp-frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend:/app
