"""Initial

Revision ID: df29f661ab85
Revises: 
Create Date: 2025-07-06 01:53:47.857891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df29f661ab85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('chest_pain_type', sa.String(length=10), nullable=False),
    sa.Column('resting_bp', sa.Integer(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('fasting_bs', sa.Integer(), nullable=False),
    sa.Column('resting_ecg', sa.String(length=50), nullable=False),
    sa.Column('max_hr', sa.Integer(), nullable=False),
    sa.Column('exercise_angina', sa.Boolean(), nullable=False),
    sa.Column('oldpeak', sa.Float(), nullable=False),
    sa.Column('st_slope', sa.String(length=10), nullable=False),
    sa.Column('heart_disease', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
